#!/usr/bin/env python3
"""Generate supabase/migrate-wix.sql from a Wix API snapshot.

Input:  supabase/wix-export.json  (gitignored — contains guest PII)
        {"events": [{id, title, startDate, tz}], "guests": [Wix guest records]}
        Pulled via the Wix Events API (events/v3/events/query and
        events/v2/guests/query with fields=GUEST_DETAILS).

Output: supabase/migrate-wix.sql   (gitignored) — idempotent; run in the
        Supabase SQL editor. Safe to rerun.
        supabase/devotional-guests.csv (gitignored) — kick-off devotional
        roster for the team's records (not imported; the devotional is
        informational on the new site).

Guests are joined to their tour slot exactly, by Wix event id.
"""

import csv
import json
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
DOWNLOADS = Path.home() / "Downloads"
SNAPSHOT = ROOT / "supabase" / "wix-export.json"
OUT_SQL = ROOT / "supabase" / "migrate-wix.sql"
OUT_DEVOTIONAL = ROOT / "supabase" / "devotional-guests.csv"

TOUR_TITLE = "Ancient Tabernacle Tour Experience"
DEVOTIONAL_TITLE = "Tabernacle Community Kick Off Devotional"
SLOT_MINUTES = 20
CAPACITY = 15  # Wix auto-closed slots at 15 guests


def esc(s: str) -> str:
    return (s or "").replace("'", "''").strip()


def legacy_csv_rows():
    """Rows inserted by the retired CSV-based import (June 21 only). Their
    timestamps were Wix's UTF-16 guest-list exports — Denver-local, second
    precision — which can't be matched against API timestamps, so the SQL
    deletes them explicitly before importing. No-op if that import never ran.
    """
    rows = []
    for path in DOWNLOADS.glob("Ancient Tabernacle Tour Guest List*.csv"):
        for g in csv.DictReader(path.open(encoding="utf-16"), delimiter="\t"):
            name = f"{g['First name'].strip()} {g['Last name'].strip()}".strip()
            rows.append((name, g["Email"].strip().lower(),
                         int(g["Total guests"] or 1), g["Timestamp"].strip()))
    return sorted(set(rows))


def main():
    data = json.loads(SNAPSHOT.read_text())

    # ── Events → local-time slots ──
    slots = {}  # (date, "HH:MM") -> end "HH:MM"
    event_slot = {}  # event id -> (date, "HH:MM")
    devotional_ids = set()
    for e in data["events"]:
        if e["title"] == DEVOTIONAL_TITLE:
            devotional_ids.add(e["id"])
            continue
        if e["title"] != TOUR_TITLE:
            continue
        start = datetime.fromisoformat(e["startDate"].replace("Z", "+00:00"))
        local = start.astimezone(ZoneInfo(e.get("tz") or "America/Denver"))
        key = (local.date().isoformat(), local.strftime("%H:%M"))
        slots[key] = (local + timedelta(minutes=SLOT_MINUTES)).strftime("%H:%M")
        event_slot[e["id"]] = key

    # ── Guests ──
    reservations, devotional, skipped = [], [], []
    for g in data["guests"]:
        if g.get("attendanceStatus") != "ATTENDING":
            continue
        d = g.get("guestDetails", {})
        name = f"{(d.get('firstName') or '').strip()} {(d.get('lastName') or '').strip()}".strip() or "Guest"
        email = (d.get("email") or "").strip().lower()
        party = max(1, min(20, int(g.get("totalGuests") or 1)))
        created = g.get("createdDate", "")
        if g["eventId"] in devotional_ids:
            devotional.append((name, email, party, created))
            continue
        key = event_slot.get(g["eventId"])
        if key is None:
            skipped.append((name, email, g["eventId"]))
            continue
        reservations.append(dict(slot=key, name=name, email=email, party=party, created=created))

    reservations.sort(key=lambda r: (r["slot"], r["created"]))
    total = sum(r["party"] for r in reservations)

    # Wix allowed duplicate occurrences at the same start time (June 21 2:30 PM
    # exists twice, 15 guests each). Those merge into one slot here, so lift
    # capacity to the real booked count where it exceeds the default.
    booked = {}
    for r in reservations:
        booked[r["slot"]] = booked.get(r["slot"], 0) + r["party"]
    capacity = {key: max(CAPACITY, booked.get(key, 0)) for key in slots}
    print(f"slots: {len(slots)} | reservations: {len(reservations)} rows / {total} guests "
          f"| devotional: {len(devotional)} rsvps / {sum(p for *_, p, _ in [(0,0,d[2],0) for d in devotional])} guests"
          .replace("  ", " "))
    if skipped:
        print(f"!! {len(skipped)} guests on unknown events skipped:", skipped[:5])

    # ── Devotional roster CSV ──
    with OUT_DEVOTIONAL.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["name", "email", "total_guests", "rsvp_at"])
        w.writerows(devotional)

    # ── SQL ──
    legacy = legacy_csv_rows()
    lines = [
        "-- Generated by scripts/generate-wix-import.py from the Wix API snapshot.",
        f"-- {len(slots)} tour slots (capacity {CAPACITY}), {len(reservations)} reservations / {total} guests.",
        "-- Guests joined to slots exactly by Wix event id. Idempotent — safe to rerun.",
        "",
        "-- ── 0. Remove rows from the retired CSV-based import, if it was run ──",
        "-- (matched exactly on name/email/party/timestamp; no-op otherwise)",
        "delete from public.reservations",
        " where (name, lower(email), party_size, created_at) in (",
        ",\n".join(
            f"  ('{esc(n)}', '{esc(e)}', {p}, '{t}'::timestamptz)" for n, e, p, t in legacy
        ),
        ");",
        "",
        "-- ── 1. Tour slots (authoritative Wix schedule) ──",
        "insert into public.tour_slots (slot_date, start_time, end_time, capacity) values",
        ",\n".join(f"  ('{d}', '{t}', '{end}', {capacity[(d, t)]})" for (d, t), end in sorted(slots.items())),
        "on conflict (slot_date, start_time) do update",
        "  set end_time = excluded.end_time, capacity = excluded.capacity;",
        "",
        "-- Remove seeded slots that were never on the real Wix schedule (none have",
        "-- reservations; new-site bookings are protected by the not-exists guard).",
        "delete from public.tour_slots s",
        " where not exists (select 1 from public.reservations r where r.slot_id = s.id)",
        "   and (s.slot_date::text, to_char(s.start_time, 'HH24:MI')) not in (",
        ",\n".join(f"  ('{d}', '{t}')" for (d, t) in sorted(slots)),
        ");",
        "",
        "-- ── 2. Reservations ──",
        "do $$",
        "declare",
        "  rec record;",
        "  v_slot_id uuid;",
        "  v_code text;",
        "  v_inserted int := 0;",
        "begin",
        "  for rec in",
        "    select * from (values",
    ]
    rows = [
        f"      ('{r['slot'][0]}', '{r['slot'][1]}', '{esc(r['name'])}', "
        f"'{esc(r['email'])}', {r['party']}, '{r['created']}')"
        for r in reservations
    ]
    lines.append(",\n".join(rows))
    lines.append("""    ) as t(slot_date, start_time, guest_name, guest_email, party, rsvp_at)
  loop
    select id into v_slot_id
      from public.tour_slots
     where slot_date = rec.slot_date::date and start_time = rec.start_time::time;
    if v_slot_id is null then
      raise exception 'No slot for % %', rec.slot_date, rec.start_time;
    end if;

    -- Skip rows already imported (rerun-safe)
    if exists (
      select 1 from public.reservations
       where slot_id = v_slot_id
         and lower(email) = rec.guest_email
         and name = rec.guest_name
         and created_at = rec.rsvp_at::timestamptz
    ) then continue; end if;

    loop
      v_code := 'CRT-' || upper(substr(md5(gen_random_uuid()::text), 1, 5));
      exit when not exists (select 1 from public.reservations where confirmation_code = v_code);
    end loop;

    insert into public.reservations
      (slot_id, name, email, party_size, status, confirmation_code, created_at)
    values
      (v_slot_id, rec.guest_name, rec.guest_email, rec.party, 'confirmed', v_code, rec.rsvp_at::timestamptz);
    v_inserted := v_inserted + 1;
  end loop;
  raise notice 'Imported % new reservations', v_inserted;
end $$;

-- ── 3. Kick-off devotional: real time (was seeded as TBA) ──
update public.events
   set start_time = '18:00', end_time = '19:00'
 where title = 'Community Kick-Off Devotional' and event_date = '2026-06-20';""")

    OUT_SQL.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_SQL}")
    print(f"wrote {OUT_DEVOTIONAL}")


if __name__ == "__main__":
    main()
